site_name: PomoBar
site_url: https://semanticdata.github.io/obsidian-pomodoro/
site_description: Documentation for the PomoBar plugin for Obsidian.
repo_url: https://github.com/semanticdata/obsidian-pomodoro
repo_name: PomoBar
# edit_uri: edit/master/docs/
site_author: Miguel Pimentel
copyright: Copyright &copy; 2025 <a href="https://github.com/semanticdata" target="_blank" rel="noopener">Miguel Pimentel</a>
theme:
    name: material
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - search.suggest
        - search.highlight
        - navigation.footer
        - content.action.edit
        - content.tabs.link
plugins:
    - search
nav:
    - "index.md"
    - "installation.md"
    - "usage.md"
    - "configuration.md"
    - "customization.md"
    - "troubleshooting.md"
    - "development.md"
    - "api.md"
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/semanticdata/
          name: semanticdata on GitHub
