site_name: PomoBar
site_url: https://semanticdata.github.io/obsidian-pomodoro/
site_description: Documentation for the PomoBar plugin for Obsidian.
repo_url: https://github.com/semanticdata/obsidian-pomodoro
# repo_name: semanticdata/obsidian-pomodoro
# edit_uri: edit/main/docs/
theme:
    name: material
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - search.suggest
        - search.highlight
        - navigation.footer
        - content.action.edit
plugins:
    - search
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Configuration: configuration.md
    - Troubleshooting: troubleshooting.md
    - Development: development.md
    - API Reference: api.md
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/semanticdata/obsidian-pomodoro
          name: PomoBar on GitHub
copyright: Copyright &copy; 2024 Miguel Pimentel
