site_name: PomoBar
site_url: https://semanticdata.github.io/obsidian-pomodoro/
site_description: Documentation for the PomoBar plugin for Obsidian.
repo_url: https://github.com/semanticdata/obsidian-pomodoro
repo_name: PomoBar
# edit_uri: edit/master/docs/
site_author: Miguel Pimentel
copyright: Copyright &copy; 2025 Miguel Pimentel
theme:
    name: material
    icon:
        logo: material/timer
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep orange
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: deep orange
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - search.suggest
        - search.highlight
        - content.tabs.link
        - navigation.footer
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        - navigation.top
        # - navigation.expand
        # - content.action.edit
        # - content.action.view
nav:
    - "Getting Started":
          - "Introduction": index.md
          - "Installation": installation.md
    - "Guides":
          - "Usage": usage.md
          - "Configuration": configuration.md
          - "Customization": customization.md
          - "Troubleshooting": troubleshooting.md
          - "Use Cases & Workflows": use-cases.md
          - "FAQ": faq.md
    - "Development":
          - "Contributing": development.md
          - "API Reference": api.md
    - "Changelog": changelog.md
plugins:
    - search
    - minify:
          minify_html: true
          minify_js: true
          minify_css: true
          htmlmin_opts:
              remove_comments: true
          cache_safe: true
    - git-authors:
          enabled: false
          show_email_address: true
          href: "https://github.com/semanticdata/"
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/semanticdata/
          name: semanticdata on GitHub
        # - icon: fontawesome/brands/codepen
        #   link: https://codepen.io/semanticdata
        #   name: semanticdata on Codepen
